/**
 * Official Innovation Taxonomy Categories
 * Standard reference categories used for discipline selection and matchmaking.
 */
export const INITIAL_CATEGORIES = [
  {
    id: '93fe2938-c843-4fa4-8b01-b07d59990023',
    name: 'Technology',
    slug: 'technology',
    description: 'Autonomous agents, foundation models, perception pipelines, distributed web, and software systems.',
    icon: 'BrainCircuit',
    accentColor: '#9B8AE5' // Soft Lavender
  },
  {
    id: '9dbbcd45-778e-411c-92cc-debee85d7137',
    name: 'Education',
    slug: 'education',
    description: 'Adaptive learning environments, spatial comprehension tools, and pedagogical software.',
    icon: 'BookOpen',
    accentColor: '#7186D8' // Soft Periwinkle
  },
  {
    id: '19b552c7-2ed6-44fe-9846-5d1501b1104f',
    name: 'Healthcare',
    slug: 'healthcare',
    description: 'Clinical diagnostics, bioinformatics, patient experience systems, and medtech hardware.',
    icon: 'Activity',
    accentColor: '#D86B9A' // Rose Pink
  },
  {
    id: 'e6fa521c-f84c-42f6-9c7d-88447ee259cc',
    name: 'Sustainability',
    slug: 'sustainability',
    description: 'Clean energy, carbon tracking, circular packaging, and regenerative natural systems.',
    icon: 'Leaf',
    accentColor: '#69B89A' // Soft Green
  },
  {
    id: '3d3d928f-2a11-4639-83d5-865730960135',
    name: 'Community',
    slug: 'community',
    description: 'Civic collaboration, local service networks, teammate matching, and shared infrastructure.',
    icon: 'Users',
    accentColor: '#58B8AD' // Fresh Teal
  },
  {
    id: 'f6f8323c-942e-4f3d-a447-48a3aa63f494',
    name: 'Finance',
    slug: 'finance',
    description: 'Group expense settlements, student budget planning, micro-payments, and transparent ledgers.',
    icon: 'DollarSign',
    accentColor: '#E9B45B' // Warm Amber
  },
  {
    id: 'a1b2c3d4-e5f6-7890-1234-56789abcdef0',
    name: 'Productivity',
    slug: 'productivity',
    description: 'Focused deep work, digital queues, cognitive workflows, and personal goal management.',
    icon: 'CheckSquare',
    accentColor: '#9B8AE5'
  },
  {
    id: 'b2c3d4e5-f6a7-8901-2345-6789abcdef01',
    name: 'Creator Economy',
    slug: 'creator-economy',
    description: 'Evidence-based portfolios, verified achievements, freelance tools, and digital creator assets.',
    icon: 'Sparkles',
    accentColor: '#E76F82'
  },
  {
    id: 'c3d4e5f6-a7b8-9012-3456-789abcdef012',
    name: 'Agriculture',
    slug: 'agriculture',
    description: 'Local produce marketplaces, crop demand matching, and farmer supply chain transparency.',
    icon: 'Wheat',
    accentColor: '#84CC16'
  },
  {
    id: 'd4e5f6a7-b8c9-0123-4567-89abcdef0123',
    name: 'Career',
    slug: 'career',
    description: 'Internship tracking, skill roadmap progression, and early-career interview management.',
    icon: 'Briefcase',
    accentColor: '#0EA5E9'
  },
  {
    id: 'e5f6a7b8-c9d0-1234-5678-9abcdef01234',
    name: 'Events',
    slug: 'events',
    description: 'Campus workshop discovery, hackathon calendars, and personalized event notifications.',
    icon: 'Calendar',
    accentColor: '#F97316'
  },
  {
    id: 'f6a7b8c9-d0e1-2345-6789-abcdef012345',
    name: 'Research',
    slug: 'research',
    description: 'Academic topic discovery, literature collaboration, and peer researcher network.',
    icon: 'Microscope',
    accentColor: '#6366F1'
  },
  {
    id: 'a7b8c9d0-e1f2-3456-789a-bcdef0123456',
    name: 'Innovation',
    slug: 'innovation',
    description: 'Algorithmic reviewer matching, idea validation signals, and structured peer critiques.',
    icon: 'Flame',
    accentColor: '#EC4899'
  }
];

/**
 * INNOVEXA — 20 Verified Seed Projects
 * Explicitly labeled as DEMO DATA for realistic explore, comparison, review, and telemetry testing.
 */
export const SEED_20_PROJECTS = [
  {
    id: 'proj_studyflow',
    project_id: 'proj_studyflow',
    title: 'StudyFlow',
    tagline: 'Personalized student workspace combining notes, deadlines, revision plans and progress.',
    short_description: 'Personalized student workspace combining notes, deadlines, revision plans and progress tracking in one place.',
    category_id: '9dbbcd45-778e-411c-92cc-debee85d7137',
    category_name: 'Education',
    project_type: 'product',
    creation_type: 'PRODUCT',
    innovation_type: 'PRODUCT',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Students struggle to organize notes, assignments, deadlines and revision in one place.',
    proposed_solution: 'A personalized student workspace combining notes, deadlines, revision plans and progress.',
    target_users: 'College students, University students',
    differentiation: 'Focus specifically on student academic workflows rather than general-purpose workspaces.',
    existing_solution_name: 'Notion',
    existing_solution_url: 'https://www.notion.com/?utm_source=chatgpt.com',
    features: ['Semester syllabus organizer', 'Assignment deadline timeline', 'Spaced-repetition revision schedules', 'Academic progress scorecard'],
    tags: ['students', 'productivity', 'education', 'planning'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 32,
    sentiment_distribution: { positive: 68, constructive: 24, critical: 8 },
    version: 1,
    has_live_product: true,
    website_url: 'https://studyflow.edu.demo',
    demo_url: 'https://studyflow.edu.demo/workspace',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-01T09:00:00Z').toISOString(),
    updated_at: new Date('2026-08-01T09:00:00Z').toISOString()
  },
  {
    id: 'proj_foodsave',
    project_id: 'proj_foodsave',
    title: 'FoodSave',
    tagline: 'Connect surplus food providers with nearby consumers before food goes to waste.',
    short_description: 'Connect surplus food providers with nearby users before food is wasted.',
    category_id: 'e6fa521c-f84c-42f6-9c7d-88447ee259cc',
    category_name: 'Sustainability',
    project_type: 'startup',
    creation_type: 'STARTUP',
    innovation_type: 'STARTUP',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Restaurants and stores often have surplus food while nearby people still need affordable meals.',
    proposed_solution: 'Connect surplus food providers with nearby users before food is wasted.',
    target_users: 'Restaurants, bakeries, supermarkets, students',
    differentiation: 'Focus on smaller local businesses and campus communities.',
    existing_solution_name: 'Too Good To Go',
    existing_solution_url: 'https://www.toogoodtogo.com/?utm_source=chatgpt.com',
    features: ['Hyperlocal surplus grocery alerts', 'Direct discount meal reservation', 'Campus pickup point network', 'Community waste prevention meter'],
    tags: ['food-waste', 'sustainability', 'local', 'marketplace'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 45,
    sentiment_distribution: { positive: 76, constructive: 18, critical: 6 },
    version: 1,
    has_live_product: true,
    website_url: 'https://foodsave.eco.demo',
    demo_url: 'https://foodsave.eco.demo/map',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-02T10:00:00Z').toISOString(),
    updated_at: new Date('2026-08-02T10:00:00Z').toISOString()
  },
  {
    id: 'proj_skillbridge',
    project_id: 'proj_skillbridge',
    title: 'SkillBridge',
    tagline: 'Map career goals to practical skills, projects, learning resources and progress.',
    short_description: 'Map career goals to skills, projects, learning resources and progress.',
    category_id: '9dbbcd45-778e-411c-92cc-debee85d7137',
    category_name: 'Education',
    project_type: 'idea',
    creation_type: 'IDEA',
    innovation_type: 'IDEA',
    project_stage: 'concept',
    development_stage: 'CONCEPT',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Students struggle to identify which practical skills they need for specific careers.',
    proposed_solution: 'Map career goals to skills, projects, learning resources and progress.',
    target_users: 'Students and fresh graduates',
    differentiation: 'Instead of primarily providing courses, connect career goals → skills → projects → evidence.',
    existing_solution_name: 'Coursera',
    existing_solution_url: 'https://www.coursera.org/?utm_source=chatgpt.com',
    features: ['Target role competency matrix', 'Project-based evidence builder', 'Minimal step-by-step roadmap', 'Peer review collision'],
    tags: ['career', 'skills', 'students', 'projects'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 38,
    sentiment_distribution: { positive: 72, constructive: 22, critical: 6 },
    version: 1,
    has_live_product: false,
    website_url: null,
    demo_url: null,
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-03T11:00:00Z').toISOString(),
    updated_at: new Date('2026-08-03T11:00:00Z').toISOString()
  },
  {
    id: 'proj_carecircle',
    project_id: 'proj_carecircle',
    title: 'CareCircle',
    tagline: 'Shared family care coordination for elder appointments, tasks, reminders and updates.',
    short_description: 'Shared family care coordination for appointments, tasks, reminders and updates.',
    category_id: '19b552c7-2ed6-44fe-9846-5d1501b1104f',
    category_name: 'Healthcare',
    project_type: 'startup',
    creation_type: 'STARTUP',
    innovation_type: 'STARTUP',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Families struggle to coordinate non-emergency care tasks for elderly relatives.',
    proposed_solution: 'Shared family care coordination for appointments, tasks, reminders and updates.',
    target_users: 'Families and caregivers',
    differentiation: 'Focus on coordination between existing family members rather than primarily finding caregivers.',
    existing_solution_name: 'Care.com',
    existing_solution_url: 'https://www.care.com/?utm_source=chatgpt.com',
    features: ['Multi-member family schedule roster', 'Medication checklist & verification', 'Emergency health history vault', 'Daily wellness checkins'],
    tags: ['caregiving', 'family', 'healthcare', 'coordination'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 29,
    sentiment_distribution: { positive: 74, constructive: 20, critical: 6 },
    version: 1,
    has_live_product: true,
    website_url: 'https://carecircle.health.demo',
    demo_url: 'https://carecircle.health.demo/app',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-04T12:00:00Z').toISOString(),
    updated_at: new Date('2026-08-04T12:00:00Z').toISOString()
  },
  {
    id: 'proj_localfix',
    project_id: 'proj_localfix',
    title: 'LocalFix',
    tagline: 'Community-based local service discovery, availability comparison and recommendation.',
    short_description: 'Community-based local service discovery and recommendation platform.',
    category_id: '3d3d928f-2a11-4639-83d5-865730960135',
    category_name: 'Community',
    project_type: 'product',
    creation_type: 'PRODUCT',
    innovation_type: 'PRODUCT',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'People have difficulty finding reliable local service providers and comparing their availability.',
    proposed_solution: 'Community-based local service discovery and recommendation platform.',
    target_users: 'Consumers and local service providers',
    differentiation: 'Focus specifically on service reliability, availability and community feedback.',
    existing_solution_name: 'Google Maps',
    existing_solution_url: 'https://www.google.com/maps/?utm_source=chatgpt.com',
    features: ['Verified customer repair logs', 'Real-time technician availability slots', 'Transparent fee estimates', 'Neighborhood trust index'],
    tags: ['local-services', 'trust', 'reviews', 'discovery'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 22,
    sentiment_distribution: { positive: 65, constructive: 27, critical: 8 },
    version: 1,
    has_live_product: true,
    website_url: 'https://localfix.community.demo',
    demo_url: 'https://localfix.community.demo/browse',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-05T13:00:00Z').toISOString(),
    updated_at: new Date('2026-08-05T13:00:00Z').toISOString()
  },
  {
    id: 'proj_campusloop',
    project_id: 'proj_campusloop',
    title: 'CampusLoop',
    tagline: 'Single unified college information, events, and opportunity discovery hub.',
    short_description: 'One campus information and opportunity hub.',
    category_id: '9dbbcd45-778e-411c-92cc-debee85d7137',
    category_name: 'Education',
    project_type: 'product',
    creation_type: 'PRODUCT',
    innovation_type: 'PRODUCT',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'College announcements, events and opportunities are scattered across WhatsApp groups and portals.',
    proposed_solution: 'One campus information and opportunity hub.',
    target_users: 'Students, faculty and clubs',
    differentiation: 'Focus exclusively on campus discovery rather than general collaboration.',
    existing_solution_name: 'Microsoft Teams',
    existing_solution_url: 'https://www.microsoft.com/microsoft-teams/?utm_source=chatgpt.com',
    features: ['Verified student club board', 'Direct workshop registration', 'Granular channel alert preferences', 'Peer opportunity collisions'],
    tags: ['college', 'events', 'students', 'community'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 51,
    sentiment_distribution: { positive: 79, constructive: 16, critical: 5 },
    version: 1,
    has_live_product: true,
    website_url: 'https://campusloop.edu.demo',
    demo_url: 'https://campusloop.edu.demo/feed',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-06T14:00:00Z').toISOString(),
    updated_at: new Date('2026-08-06T14:00:00Z').toISOString()
  },
  {
    id: 'proj_billsplit_smart',
    project_id: 'proj_billsplit_smart',
    title: 'BillSplit Smart',
    tagline: 'Track irregular group expenses and calculate transparent, fair settlements.',
    short_description: 'Track irregular group expenses and calculate transparent settlements.',
    category_id: 'f6f8323c-942e-4f3d-a447-48a3aa63f494',
    category_name: 'Finance',
    project_type: 'idea',
    creation_type: 'IDEA',
    innovation_type: 'IDEA',
    project_stage: 'concept',
    development_stage: 'CONCEPT',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Shared expenses become confusing when people pay different amounts at different times.',
    proposed_solution: 'Track irregular group expenses and calculate transparent settlements.',
    target_users: 'Students, roommates, friends',
    differentiation: 'Focus on irregular expenses and student groups.',
    existing_solution_name: 'Splitwise',
    existing_solution_url: 'https://www.splitwise.com/?utm_source=chatgpt.com',
    features: ['Multi-currency receipt scanner', 'Proportional bill division algorithms', 'Instant UPI / settlement links', 'Shared household expense ledger'],
    tags: ['expenses', 'students', 'payments', 'groups'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 27,
    sentiment_distribution: { positive: 70, constructive: 23, critical: 7 },
    version: 1,
    has_live_product: false,
    website_url: null,
    demo_url: null,
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-07T15:00:00Z').toISOString(),
    updated_at: new Date('2026-08-07T15:00:00Z').toISOString()
  },
  {
    id: 'proj_refillroute',
    project_id: 'proj_refillroute',
    title: 'RefillRoute',
    tagline: 'Map nearby packaging-free refill stations and reusable-product inventory.',
    short_description: 'Map refill stations and reusable-product availability.',
    category_id: 'e6fa521c-f84c-42f6-9c7d-88447ee259cc',
    category_name: 'Sustainability',
    project_type: 'startup',
    creation_type: 'STARTUP',
    innovation_type: 'STARTUP',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Consumers want to reduce packaging waste but cannot easily find nearby refill locations.',
    proposed_solution: 'Map refill stations and reusable-product availability.',
    target_users: 'Environment-conscious consumers',
    differentiation: 'Hyperlocal verified stock and refill container compatibility guide.',
    existing_solution_name: 'Zero Waste App',
    existing_solution_url: 'https://www.zerowaste.app/?utm_source=chatgpt.com',
    features: ['Live bulk refill inventory maps', 'Packaging waste saved calculator', 'Community store crowd-verification', 'Refill station checkin rewards'],
    tags: ['refill', 'environment', 'maps', 'sustainability'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 34,
    sentiment_distribution: { positive: 73, constructive: 21, critical: 6 },
    version: 1,
    has_live_product: true,
    website_url: 'https://refillroute.eco.demo',
    demo_url: 'https://refillroute.eco.demo/locator',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-08T16:00:00Z').toISOString(),
    updated_at: new Date('2026-08-08T16:00:00Z').toISOString()
  },
  {
    id: 'proj_focusspace',
    project_id: 'proj_focusspace',
    title: 'FocusSpace',
    tagline: 'Adaptive focus sessions with personal goals, breaks and distraction telemetry.',
    short_description: 'Adaptive focus sessions with goals, breaks and distraction tracking.',
    category_id: 'a1b2c3d4-e5f6-7890-1234-56789abcdef0',
    category_name: 'Productivity',
    project_type: 'product',
    creation_type: 'PRODUCT',
    innovation_type: 'PRODUCT',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Students and remote workers struggle to maintain focused work sessions.',
    proposed_solution: 'Adaptive focus sessions with goals, breaks and distraction tracking.',
    target_users: 'Students and remote workers',
    differentiation: 'Combine focus sessions with measurable personal goals rather than only a timer.',
    existing_solution_name: 'Forest',
    existing_solution_url: 'https://www.forestapp.cc/?utm_source=chatgpt.com',
    features: ['Contextual deep work timers', 'Distraction friction prompts', 'Weekly cognitive output graphs', 'Accountability peer rooms'],
    tags: ['focus', 'students', 'productivity'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 41,
    sentiment_distribution: { positive: 69, constructive: 25, critical: 6 },
    version: 1,
    has_live_product: true,
    website_url: 'https://focusspace.app.demo',
    demo_url: 'https://focusspace.app.demo/timer',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-09T17:00:00Z').toISOString(),
    updated_at: new Date('2026-08-09T17:00:00Z').toISOString()
  },
  {
    id: 'proj_projectmatch',
    project_id: 'proj_projectmatch',
    title: 'ProjectMatch',
    tagline: 'Match students based on interests, skills, availability and project requirements.',
    short_description: 'Match people based on interests, skills, availability and project requirements.',
    category_id: '3d3d928f-2a11-4639-83d5-865730960135',
    category_name: 'Community',
    project_type: 'startup',
    creation_type: 'STARTUP',
    innovation_type: 'STARTUP',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Students with complementary skills struggle to find suitable project teammates.',
    proposed_solution: 'Match people based on interests, skills, availability and project requirements.',
    target_users: 'Students, Hackathon Builders',
    differentiation: 'Match specifically around project requirements, skills and availability.',
    existing_solution_name: 'LinkedIn',
    existing_solution_url: 'https://www.linkedin.com/?utm_source=chatgpt.com',
    features: ['Verified skill badge verification', 'Hackathon teammate matchmaking', 'Schedule availability overlap checker', 'Project role definition builder'],
    tags: ['students', 'teams', 'projects', 'skills'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 62,
    sentiment_distribution: { positive: 81, constructive: 15, critical: 4 },
    version: 1,
    has_live_product: true,
    website_url: 'https://projectmatch.co.demo',
    demo_url: 'https://projectmatch.co.demo/match',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-10T18:00:00Z').toISOString(),
    updated_at: new Date('2026-08-10T18:00:00Z').toISOString()
  },
  {
    id: 'proj_medrecord_vault',
    project_id: 'proj_medrecord_vault',
    title: 'MedRecord Vault',
    tagline: 'Secure personal health-document organization, OCR scanning and retrieval.',
    short_description: 'Secure personal health-document organization and retrieval.',
    category_id: '19b552c7-2ed6-44fe-9846-5d1501b1104f',
    category_name: 'Healthcare',
    project_type: 'product',
    creation_type: 'PRODUCT',
    innovation_type: 'PRODUCT',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'People often have medical reports scattered across phones, email and physical documents.',
    proposed_solution: 'Secure personal health-document organization and retrieval.',
    target_users: 'Patients and families',
    differentiation: 'Health-focused document organization with smart parameter extraction.',
    existing_solution_name: 'Google Drive',
    existing_solution_url: 'https://drive.google.com/?utm_source=chatgpt.com',
    features: ['Lab report OCR parameter tracker', 'Prescription expiry alerts', 'Emergency medical contact card', 'End-to-end encrypted storage'],
    tags: ['healthcare', 'records', 'privacy', 'medical'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 35,
    sentiment_distribution: { positive: 75, constructive: 19, critical: 6 },
    version: 1,
    has_live_product: true,
    website_url: 'https://medrecordvault.health.demo',
    demo_url: 'https://medrecordvault.health.demo/vault',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-11T10:00:00Z').toISOString(),
    updated_at: new Date('2026-08-11T10:00:00Z').toISOString()
  },
  {
    id: 'proj_creatorproof',
    project_id: 'proj_creatorproof',
    title: 'CreatorProof',
    tagline: 'Structured portfolio builder showing projects, measurable outcomes and verified contributions.',
    short_description: 'Build a structured portfolio showing projects, outcomes and verified contributions.',
    category_id: 'b2c3d4e5-f6a7-8901-2345-6789abcdef01',
    category_name: 'Creator Economy',
    project_type: 'idea',
    creation_type: 'IDEA',
    innovation_type: 'IDEA',
    project_stage: 'concept',
    development_stage: 'CONCEPT',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Small creators struggle to organize evidence of their work and measurable achievements.',
    proposed_solution: 'Build a structured portfolio showing projects, outcomes and verified contributions.',
    target_users: 'Small creators, Freelancers, Indie builders',
    differentiation: 'Evidence-based creator portfolio with verifiable outcome metrics.',
    existing_solution_name: 'Canva',
    existing_solution_url: 'https://www.canva.com/?utm_source=chatgpt.com',
    features: ['Client testimonial verification', 'Live analytics widget embed', 'Case study proof templates', 'Custom domain publishing'],
    tags: ['creators', 'portfolio', 'evidence', 'freelance'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 42,
    sentiment_distribution: { positive: 78, constructive: 17, critical: 5 },
    version: 1,
    has_live_product: false,
    website_url: null,
    demo_url: null,
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-12T11:00:00Z').toISOString(),
    updated_at: new Date('2026-08-12T11:00:00Z').toISOString()
  },
  {
    id: 'proj_farmconnect',
    project_id: 'proj_farmconnect',
    title: 'FarmConnect',
    tagline: 'Local agricultural marketplace connecting farmers with nearby wholesale and retail buyers.',
    short_description: 'Local marketplace connecting farmers with potential buyers.',
    category_id: 'c3d4e5f6-a7b8-9012-3456-789abcdef012',
    category_name: 'Agriculture',
    project_type: 'startup',
    creation_type: 'STARTUP',
    innovation_type: 'STARTUP',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Small farmers may struggle to discover nearby buyers and compare demand.',
    proposed_solution: 'Local marketplace connecting farmers with potential buyers.',
    target_users: 'Small farmers and produce buyers',
    differentiation: 'Local agricultural demand matching with transparent price signals.',
    existing_solution_name: 'IndiaMART',
    existing_solution_url: 'https://www.indiamart.com/?utm_source=chatgpt.com',
    features: ['Direct crop harvest listings', 'Mandis price trend comparison', 'Buyer escrow milestone payment', 'Local logistics coordinator matching'],
    tags: ['agriculture', 'farmers', 'marketplace', 'food'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 37,
    sentiment_distribution: { positive: 80, constructive: 14, critical: 6 },
    version: 1,
    has_live_product: true,
    website_url: 'https://farmconnect.agri.demo',
    demo_url: 'https://farmconnect.agri.demo/market',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-13T12:00:00Z').toISOString(),
    updated_at: new Date('2026-08-13T12:00:00Z').toISOString()
  },
  {
    id: 'proj_interntrack',
    project_id: 'proj_interntrack',
    title: 'InternTrack',
    tagline: 'Central internship application tracker with reminders, stages and interview progress.',
    short_description: 'Central internship application tracker with reminders and progress.',
    category_id: 'd4e5f6a7-b8c9-0123-4567-89abcdef0123',
    category_name: 'Career',
    project_type: 'product',
    creation_type: 'PRODUCT',
    innovation_type: 'PRODUCT',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Students lose track of internship applications, deadlines, interview stages and follow-ups.',
    proposed_solution: 'Central internship application tracker with reminders and progress.',
    target_users: 'College students, Job seekers',
    differentiation: 'Application-management rather than job discovery with stage progress.',
    existing_solution_name: 'LinkedIn Jobs',
    existing_solution_url: 'https://www.linkedin.com/jobs/?utm_source=chatgpt.com',
    features: ['Kanban interview pipeline stages', 'Automated follow-up reminders', 'Resume version matching', 'Application outcome statistics'],
    tags: ['internships', 'career', 'students', 'tracking'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 49,
    sentiment_distribution: { positive: 82, constructive: 13, critical: 5 },
    version: 1,
    has_live_product: true,
    website_url: 'https://interntrack.career.demo',
    demo_url: 'https://interntrack.career.demo/board',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-14T13:00:00Z').toISOString(),
    updated_at: new Date('2026-08-14T13:00:00Z').toISOString()
  },
  {
    id: 'proj_repairshare',
    project_id: 'proj_repairshare',
    title: 'RepairShare',
    tagline: 'Electronics diagnosis guidance combined with verified local repair-provider discovery.',
    short_description: 'Product diagnosis guidance plus local repair-provider discovery.',
    category_id: 'e6fa521c-f84c-42f6-9c7d-88447ee259cc',
    category_name: 'Sustainability',
    project_type: 'startup',
    creation_type: 'STARTUP',
    innovation_type: 'STARTUP',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'People frequently discard repairable electronics because they cannot find trusted repair information or providers.',
    proposed_solution: 'Product diagnosis guidance plus local repair-provider discovery.',
    target_users: 'Consumers with damaged electronics, Repair technicians',
    differentiation: 'Combine repair knowledge with local provider discovery and repairability scores.',
    existing_solution_name: 'iFixit',
    existing_solution_url: 'https://www.ifixit.com/?utm_source=chatgpt.com',
    features: ['Device teardown step-by-step assistant', 'Local certified technician ratings', 'Spare parts price comparisons', 'E-waste diversion telemetry'],
    tags: ['repair', 'sustainability', 'electronics', 'local'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 31,
    sentiment_distribution: { positive: 77, constructive: 17, critical: 6 },
    version: 1,
    has_live_product: true,
    website_url: 'https://repairshare.eco.demo',
    demo_url: 'https://repairshare.eco.demo/diagnose',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-15T14:00:00Z').toISOString(),
    updated_at: new Date('2026-08-15T14:00:00Z').toISOString()
  },
  {
    id: 'proj_eventpulse',
    project_id: 'proj_eventpulse',
    title: 'EventPulse',
    tagline: 'Personalized student workshop discovery and calendar reminder system.',
    short_description: 'Personalized event discovery and reminder system.',
    category_id: 'e5f6a7b8-c9d0-1234-5678-9abcdef01234',
    category_name: 'Events',
    project_type: 'idea',
    creation_type: 'IDEA',
    innovation_type: 'IDEA',
    project_stage: 'concept',
    development_stage: 'CONCEPT',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Students miss useful workshops and events because information is distributed across multiple channels.',
    proposed_solution: 'Personalized event discovery and reminder system.',
    target_users: 'College students, Club organizers',
    differentiation: 'Personalized campus-focused discovery with noise reduction.',
    existing_solution_name: 'Eventbrite',
    existing_solution_url: 'https://www.eventbrite.com/?utm_source=chatgpt.com',
    features: ['Academic interest tagging engine', 'One-click calendar sync', 'Verified speaker credential badges', 'Peer attendance alerts'],
    tags: ['events', 'workshops', 'students', 'campus'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 26,
    sentiment_distribution: { positive: 71, constructive: 22, critical: 7 },
    version: 1,
    has_live_product: false,
    website_url: null,
    demo_url: null,
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-16T15:00:00Z').toISOString(),
    updated_at: new Date('2026-08-16T15:00:00Z').toISOString()
  },
  {
    id: 'proj_budgetbite',
    project_id: 'proj_budgetbite',
    title: 'BudgetBite',
    tagline: 'Budget-aware meal planning using locally available grocery and food options.',
    short_description: 'Budget-aware meal planning using locally available food options.',
    category_id: 'f6f8323c-942e-4f3d-a447-48a3aa63f494',
    category_name: 'Finance',
    project_type: 'product',
    creation_type: 'PRODUCT',
    innovation_type: 'PRODUCT',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Students struggle to plan affordable meals while staying within a daily food budget.',
    proposed_solution: 'Budget-aware meal planning using locally available food options.',
    target_users: 'Budget-conscious students and young professionals',
    differentiation: 'Food recommendations constrained by student budget and local grocery availability.',
    existing_solution_name: 'MyFitnessPal',
    existing_solution_url: 'https://www.myfitnesspal.com/?utm_source=chatgpt.com',
    features: ['Daily cost ceiling recipe generator', 'Regional pantry price index', 'Dietary preference filters (Vegan, Vegetarian)', 'Weekly grocery shopping list export'],
    tags: ['food', 'budget', 'students', 'nutrition'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 44,
    sentiment_distribution: { positive: 76, constructive: 18, critical: 6 },
    version: 1,
    has_live_product: true,
    website_url: 'https://budgetbite.app.demo',
    demo_url: 'https://budgetbite.app.demo/planner',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-17T16:00:00Z').toISOString(),
    updated_at: new Date('2026-08-17T16:00:00Z').toISOString()
  },
  {
    id: 'proj_researchcircle',
    project_id: 'proj_researchcircle',
    title: 'ResearchCircle',
    tagline: 'Academic research-topic discovery, paper synthesis and cross-institution peer collaboration.',
    short_description: 'Research-topic discovery and collaboration platform.',
    category_id: 'f6a7b8c9-d0e1-2345-6789-abcdef012345',
    category_name: 'Research',
    project_type: 'startup',
    creation_type: 'STARTUP',
    innovation_type: 'STARTUP',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'Students working on similar academic topics often work independently without discovering related work or peers.',
    proposed_solution: 'Research-topic discovery and collaboration platform.',
    target_users: 'Undergraduate and graduate researchers',
    differentiation: 'Research-topic discovery + peer collaboration and literature synthesis notes.',
    existing_solution_name: 'Google Scholar',
    existing_solution_url: 'https://scholar.google.com/?utm_source=chatgpt.com',
    features: ['Semantic paper overlap clustering', 'Shared lab notebook annotations', 'Author specialty matching', 'Preprint critique review queue'],
    tags: ['research', 'academia', 'papers', 'collaboration'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 53,
    sentiment_distribution: { positive: 79, constructive: 16, critical: 5 },
    version: 1,
    has_live_product: true,
    website_url: 'https://researchcircle.org.demo',
    demo_url: 'https://researchcircle.org.demo/discover',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-18T17:00:00Z').toISOString(),
    updated_at: new Date('2026-08-18T17:00:00Z').toISOString()
  },
  {
    id: 'proj_queueless',
    project_id: 'proj_queueless',
    title: 'QueueLess',
    tagline: 'Digital queue visibility, live wait-time estimates and remote token management.',
    short_description: 'Digital queue visibility and estimated waiting-time system.',
    category_id: 'a1b2c3d4-e5f6-7890-1234-56789abcdef0',
    category_name: 'Productivity',
    project_type: 'product',
    creation_type: 'PRODUCT',
    innovation_type: 'PRODUCT',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'People waste time waiting at clinics, service centers and campus offices.',
    proposed_solution: 'Digital queue visibility and estimated waiting-time system.',
    target_users: 'Patients, campus visitors, municipal service users',
    differentiation: 'Simple queue visibility for campuses and local services with token tracking.',
    existing_solution_name: 'Qminder',
    existing_solution_url: 'https://www.qminder.com/?utm_source=chatgpt.com',
    features: ['Live queue status dashboard', 'SMS / push turn notifications', 'Predictive wait-time AI estimator', 'Multi-department counter routing'],
    tags: ['queue', 'waiting-time', 'productivity', 'services'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 67,
    sentiment_distribution: { positive: 83, constructive: 12, critical: 5 },
    version: 1,
    has_live_product: true,
    website_url: 'https://queueless.services.demo',
    demo_url: 'https://queueless.services.demo/queue',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-19T18:00:00Z').toISOString(),
    updated_at: new Date('2026-08-19T18:00:00Z').toISOString()
  },
  {
    id: 'proj_ideapulse',
    project_id: 'proj_ideapulse',
    title: 'IdeaPulse',
    tagline: 'Algorithmic reviewer matching based on domain expertise and experience rather than random voting.',
    short_description: 'Match projects with people whose interests and experience make their feedback useful.',
    category_id: 'a7b8c9d0-e1f2-3456-789a-bcdef0123456',
    category_name: 'Innovation',
    project_type: 'startup',
    creation_type: 'STARTUP',
    innovation_type: 'STARTUP',
    project_stage: 'prototype',
    development_stage: 'PROTOTYPE',
    status: 'published',
    launch_status: 'validating',
    is_demo: true,
    demo_badge_label: 'DEMO DATA',
    problem_statement: 'New ideas often receive opinions from people who are not relevant to the problem being solved.',
    proposed_solution: 'Match projects with people whose interests and experience make their feedback useful.',
    target_users: 'Innovators, Founders, Subject-matter experts',
    differentiation: 'Reviewer matching based on relevance rather than random voting, with traceable reputation.',
    existing_solution_name: 'Piqd',
    existing_solution_url: 'https://www.piqd.tech/?utm_source=chatgpt.com',
    features: ['Discipline-based algorithmic reviewer assignment', 'Structured rubric-driven scorecards', 'Reviewer reputation & proof of critique', 'Consensus & friction analytics synthesis'],
    tags: ['innovation', 'feedback', 'validation', 'peer-review'],
    validation_target: 10,
    valid_reviews_count: 3,
    upvotes_count: 88,
    sentiment_distribution: { positive: 85, constructive: 11, critical: 4 },
    version: 1,
    has_live_product: true,
    website_url: 'https://ideapulse.network.demo',
    demo_url: 'https://ideapulse.network.demo/collision',
    user_id: 'platform_demo_desk',
    creator_name: 'INNOVEXA Editorial Desk',
    creator_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    created_at: new Date('2026-08-20T19:00:00Z').toISOString(),
    updated_at: new Date('2026-08-20T19:00:00Z').toISOString()
  }
];

/**
 * Synthetic Demo Reviews for the 20 Seed Projects
 * Explicitly marked with is_demo = true and review_type = 'DEMO'
 */
export const SEED_DEMO_REVIEWS = [
  // 01 StudyFlow Reviews
  {
    id: 'demo_rev_sf_1',
    project_id: 'proj_studyflow',
    reviewer_id: 'usr_priya_demo',
    reviewer_name: 'Priya Sharma',
    reviewer_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    reviewer_role: 'Student Product Lead',
    is_demo: true,
    review_type: 'DEMO',
    verdict: 'VALIDATED',
    rating: 5,
    problem_relevance: 'YES',
    solution_clarity: 'YES',
    usefulness: 'YES',
    feedback_text: 'The problem is very relatable. I would want automatic semester planning and deadline syncing across course portals.',
    strengths: 'Addresses real student cognitive fatigue across fragmented portals.',
    weaknesses: 'Needs seamless export so students do not feel locked into one format.',
    created_at: new Date('2026-08-05T10:00:00Z').toISOString()
  },
  {
    id: 'demo_rev_sf_2',
    project_id: 'proj_studyflow',
    reviewer_id: 'usr_amit_demo',
    reviewer_name: 'Amit Patel',
    reviewer_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    reviewer_role: 'Academic Technologist',
    is_demo: true,
    review_type: 'DEMO',
    verdict: 'VALIDATED_WITH_RESERVATIONS',
    rating: 4,
    problem_relevance: 'YES',
    solution_clarity: 'YES',
    usefulness: 'MAYBE',
    feedback_text: 'Useful concept, but students already use several productivity apps. The student-specific workflow needs to be very simple.',
    strengths: 'Clear value proposition over bloated generic tools.',
    weaknesses: 'Must avoid feature creep.',
    created_at: new Date('2026-08-06T11:00:00Z').toISOString()
  },
  {
    id: 'demo_rev_sf_3',
    project_id: 'proj_studyflow',
    reviewer_id: 'usr_rahul_demo',
    reviewer_name: 'Rahul Verma',
    reviewer_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
    reviewer_role: 'Peer Reviewer',
    is_demo: true,
    review_type: 'DEMO',
    verdict: 'VALIDATED',
    rating: 4,
    problem_relevance: 'YES',
    solution_clarity: 'YES',
    usefulness: 'YES',
    feedback_text: 'Add timetable and assignment deadline integration with Google Calendar and Canvas.',
    strengths: 'Strong niche positioning for higher education.',
    weaknesses: 'Requires continuous schedule updates.',
    created_at: new Date('2026-08-07T12:00:00Z').toISOString()
  },

  // 02 FoodSave Reviews
  {
    id: 'demo_rev_fs_1',
    project_id: 'proj_foodsave',
    reviewer_id: 'usr_meena_demo',
    reviewer_name: 'Meena Iyer',
    reviewer_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100',
    reviewer_role: 'Sustainability Researcher',
    is_demo: true,
    review_type: 'DEMO',
    verdict: 'VALIDATED',
    rating: 5,
    problem_relevance: 'YES',
    solution_clarity: 'YES',
    usefulness: 'YES',
    feedback_text: 'Strong environmental value. The waste diversion potential in university neighborhoods is significant.',
    strengths: 'High tangible community impact.',
    weaknesses: 'Food safety and pickup compliance need strict guidelines.',
    created_at: new Date('2026-08-08T10:00:00Z').toISOString()
  },
  {
    id: 'demo_rev_fs_2',
    project_id: 'proj_foodsave',
    reviewer_id: 'usr_arun_demo',
    reviewer_name: 'Arun Nair',
    reviewer_avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
    reviewer_role: 'Operations Reviewer',
    is_demo: true,
    review_type: 'DEMO',
    verdict: 'VALIDATED_WITH_RESERVATIONS',
    rating: 4,
    problem_relevance: 'YES',
    solution_clarity: 'YES',
    usefulness: 'MAYBE',
    feedback_text: 'Pickup timing could become difficult during peak closing hours for small bakeries.',
    strengths: 'Appeals directly to price-sensitive students.',
    weaknesses: 'Volatile daily inventory.',
    created_at: new Date('2026-08-09T11:00:00Z').toISOString()
  },
  {
    id: 'demo_rev_fs_3',
    project_id: 'proj_foodsave',
    reviewer_id: 'usr_karthik_demo',
    reviewer_name: 'Karthik Raja',
    reviewer_avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100',
    reviewer_role: 'Founder & Builder',
    is_demo: true,
    review_type: 'DEMO',
    verdict: 'VALIDATED',
    rating: 5,
    problem_relevance: 'YES',
    solution_clarity: 'YES',
    usefulness: 'YES',
    feedback_text: 'A nearby-distance filter and live push notification for 15-minute flash surplus deals would make this extremely useful.',
    strengths: 'Clear economic win for both merchants and students.',
    weaknesses: 'Initial merchant supply density needed.',
    created_at: new Date('2026-08-10T12:00:00Z').toISOString()
  },

  // 03 SkillBridge Reviews
  {
    id: 'demo_rev_sb_1',
    project_id: 'proj_skillbridge',
    reviewer_id: 'usr_priya_demo',
    reviewer_name: 'Priya Sharma',
    reviewer_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    reviewer_role: 'Student Product Lead',
    is_demo: true,
    review_type: 'DEMO',
    verdict: 'VALIDATED',
    rating: 5,
    problem_relevance: 'YES',
    solution_clarity: 'YES',
    usefulness: 'YES',
    feedback_text: 'The career-to-project connection is very useful. Most online courses leave you with theoretical knowledge but no proof.',
    strengths: 'Outcome-oriented instead of passive video consumption.',
    weaknesses: 'Must keep project specifications updated with industry standards.',
    created_at: new Date('2026-08-11T10:00:00Z').toISOString()
  },
  {
    id: 'demo_rev_sb_2',
    project_id: 'proj_skillbridge',
    reviewer_id: 'usr_vishal_demo',
    reviewer_name: 'Vishal Rao',
    reviewer_avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100',
    reviewer_role: 'Technical Reviewer',
    is_demo: true,
    review_type: 'DEMO',
    verdict: 'VALIDATED_WITH_RESERVATIONS',
    rating: 4,
    problem_relevance: 'YES',
    solution_clarity: 'YES',
    usefulness: 'MAYBE',
    feedback_text: 'Recommendations should not become overwhelming. Keep each track focused on 3 verifiable projects.',
    strengths: 'Clear skill mapping logic.',
    weaknesses: 'Risk of cognitive overload.',
    created_at: new Date('2026-08-12T11:00:00Z').toISOString()
  },
  {
    id: 'demo_rev_sb_3',
    project_id: 'proj_skillbridge',
    reviewer_id: 'usr_asha_demo',
    reviewer_name: 'Asha Sundaram',
    reviewer_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
    reviewer_role: 'Peer Evaluator',
    is_demo: true,
    review_type: 'DEMO',
    verdict: 'VALIDATED',
    rating: 4,
    problem_relevance: 'YES',
    solution_clarity: 'YES',
    usefulness: 'YES',
    feedback_text: 'Show a small verifiable roadmap rather than hundreds of courses.',
    strengths: 'Actionable milestone design.',
    weaknesses: 'Needs industry mentor review.',
    created_at: new Date('2026-08-13T12:00:00Z').toISOString()
  }
];

// Initial Innovations combining the 20 verified seed projects
export const INITIAL_INNOVATIONS = [...SEED_20_PROJECTS];
export const INITIAL_REVIEWS = [...SEED_DEMO_REVIEWS];
export const INITIAL_USERS = [
  {
    id: 'usr_karthick_founder',
    email: 'karthick@innovexa.ai',
    username: 'karthick',
    full_name: 'Karthick Kannan',
    name: 'Karthick Kannan',
    headline: 'Founder & Principal Architect @ INNOVEXA',
    bio: 'Pioneering structured innovation validation, evidence-backed peer review collision, and autonomous research ecosystems.',
    avatar_url: `https://api.dicebear.com/7.x/initials/svg?seed=Karthick%20Kannan&backgroundColor=20212a,e76f82,7186d8`,
    avatar: `https://api.dicebear.com/7.x/initials/svg?seed=Karthick%20Kannan&backgroundColor=20212a,e76f82,7186d8`,
    role: 'creator',
    organization: 'INNOVEXA Core Labs',
    location: 'San Francisco, CA',
    website: 'https://innovexa.ai',
    github_url: 'https://github.com/karthikannan122-sketch',
    linkedin_url: 'https://linkedin.com/in/karthick-kannan',
    interests: ['Technology', 'AI & MACHINE LEARNING', 'Sustainability'],
    skills: ['System Architecture', 'Product Innovation', 'AI Intelligence', 'Frontier Tech'],
    preferred_domains: ['Technology', 'Education', 'Sustainability'],
    credits: 150,
    reputation_score: 150,
    reputation_tier: 'MASTER VALIDATOR',
    onboarding_completed: true,
    created_at: new Date('2026-08-01T08:00:00Z').toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'platform_demo_desk',
    email: 'editorial@innovexa.ai',
    username: 'editorial_desk',
    full_name: 'INNOVEXA Editorial Desk',
    name: 'INNOVEXA Editorial Desk',
    headline: 'Curated Innovation Ledger & Benchmark Review Guild',
    bio: 'Official research desk and consensus curation team at INNOVEXA. Curating verified innovation specimens across technology, education, healthcare, and sustainability.',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    role: 'validator',
    organization: 'INNOVEXA Standards Institute',
    location: 'Cambridge, MA',
    website: 'https://innovexa.ai/ledger',
    github_url: 'https://github.com/karthikannan122-sketch/Innovexa',
    linkedin_url: 'https://linkedin.com/company/innovexa',
    interests: ['Technology', 'Education', 'Healthcare', 'Sustainability'],
    skills: ['Peer Critique', 'System Validation', 'Evidence Verification', 'Consensus Modeling'],
    preferred_domains: ['Technology', 'Education', 'Healthcare', 'Sustainability'],
    credits: 250,
    reputation_score: 250,
    reputation_tier: 'EXPERT CONTRIBUTOR',
    projects_count: 20,
    reviews_count: 15,
    onboarding_completed: true,
    created_at: new Date('2026-08-01T08:00:00Z').toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'usr_sarah_reviewer',
    email: 'sarah.validator@innovexa.io',
    username: 'sarah_reviewer',
    full_name: 'Sarah Jenkins',
    name: 'Sarah Jenkins',
    headline: 'Senior Systems Architect & Peer Validator',
    bio: 'Senior Systems Architect evaluating early-stage technical thesis, distributed topologies, and autonomous software resilience.',
    avatar_url: `https://api.dicebear.com/7.x/initials/svg?seed=Sarah%20Jenkins&backgroundColor=20212a,e76f82,7186d8`,
    avatar: `https://api.dicebear.com/7.x/initials/svg?seed=Sarah%20Jenkins&backgroundColor=20212a,e76f82,7186d8`,
    role: 'reviewer',
    organization: 'MIT Lincoln Labs / OpenGrid',
    location: 'Boston, MA',
    website: 'https://sarahjenkins.tech',
    github_url: 'https://github.com/sarahjenkins-tech',
    linkedin_url: 'https://linkedin.com/in/sarah-jenkins',
    interests: ['Technology', 'Sustainability', 'Productivity'],
    skills: ['Distributed Systems', 'Cloud Native', 'Go', 'Rust'],
    preferred_domains: ['Technology', 'Productivity'],
    credits: 210,
    reputation_score: 210,
    reputation_tier: 'EXPERT CONTRIBUTOR',
    onboarding_completed: true,
    created_at: new Date('2026-08-05T08:00:00Z').toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'usr_marcus_creator',
    email: 'marcus.ai@innovexa.io',
    username: 'marcus_chen',
    full_name: 'Marcus Chen',
    name: 'Marcus Chen',
    headline: 'AI Researcher & Perception Hardware Lead',
    bio: 'Developing edge vision pipelines, multi-modal robotics interfaces, and high-frequency sensor fusion models.',
    avatar_url: `https://api.dicebear.com/7.x/initials/svg?seed=Marcus%20Chen&backgroundColor=20212a,e76f82,7186d8`,
    avatar: `https://api.dicebear.com/7.x/initials/svg?seed=Marcus%20Chen&backgroundColor=20212a,e76f82,7186d8`,
    role: 'creator',
    organization: 'Stanford Robotics Group',
    location: 'Palo Alto, CA',
    website: 'https://marcuschen.ai',
    github_url: 'https://github.com/marcuschen-ai',
    linkedin_url: 'https://linkedin.com/in/marcus-chen-ai',
    interests: ['AI & MACHINE LEARNING', 'Technology', 'Healthcare'],
    skills: ['Computer Vision', 'PyTorch', 'Edge Computing', 'Robotics'],
    preferred_domains: ['Technology', 'Healthcare'],
    credits: 175,
    reputation_score: 175,
    reputation_tier: 'TRUSTED REVIEWER',
    onboarding_completed: true,
    created_at: new Date('2026-08-08T08:00:00Z').toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'usr_elena_validator',
    email: 'elena.rostova@innovexa.io',
    username: 'elena_rostova',
    full_name: 'Dr. Elena Rostova',
    name: 'Dr. Elena Rostova',
    headline: 'Bio-Informatics Fellow & Climate Tech Advisor',
    bio: 'Researching algorithmic carbon sequestration diagnostics, bio-materials validation, and computational genomic markers.',
    avatar_url: `https://api.dicebear.com/7.x/initials/svg?seed=Elena%20Rostova&backgroundColor=20212a,e76f82,7186d8`,
    avatar: `https://api.dicebear.com/7.x/initials/svg?seed=Elena%20Rostova&backgroundColor=20212a,e76f82,7186d8`,
    role: 'reviewer',
    organization: 'Oxford Climate Informatics',
    location: 'Oxford, UK',
    website: 'https://elena-rostova.org',
    github_url: 'https://github.com/elena-rostova',
    linkedin_url: 'https://linkedin.com/in/elena-rostova',
    interests: ['Sustainability', 'Healthcare', 'Research'],
    skills: ['Genomics', 'Bio-Informatics', 'Climate Analytics', 'Python'],
    preferred_domains: ['Sustainability', 'Healthcare'],
    credits: 190,
    reputation_score: 190,
    reputation_tier: 'TRUSTED REVIEWER',
    onboarding_completed: true,
    created_at: new Date('2026-08-10T08:00:00Z').toISOString(),
    updated_at: new Date().toISOString()
  }
];

export const INITIAL_FEATURED_DEMOS = SEED_20_PROJECTS.slice(0, 4);
export const INITIAL_ASSIGNMENTS = [];
export const INITIAL_COMMENTS = [];
export const INITIAL_NOTIFICATIONS = [];
export const INITIAL_UPVOTES = [];
export const INITIAL_EXTERNAL_INNOVATIONS = [];
export const INITIAL_EXTERNAL_SOURCES = [];
export const INITIAL_COMMUNITY_POSTS = [];
export const INITIAL_COMMUNITY_COMMENTS = [];
export const INITIAL_COMMUNITY_RESOURCES = [];
export const INITIAL_VOTES = [];
